[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
bytecount = "0.6.2"
nom = "7.0.0"
num = "0.4.0"
itertools = "0.10.1"
lazy_static = "1.4.0"
rayon = "1.5.1"
pathfinding = "2.1.1"
nohash-hasher = "0.2.0"
